// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfvprhpmykrrvuucaaak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmdnByaHBteWtycnZ1dWNhYWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTg2MjcsImV4cCI6MjA3MDQ5NDYyN30.ew48QvdnGLa8yo9ts_5HUMqW82IzD2mVR0mrnVF5D9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});